In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
veri=pd.read_csv('wine.csv')
y=veri['Customer_Segment']
x=veri.drop(['Customer_Segment'],axis=1)

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=18)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [18]:
#PCA
#Verinin boyutlarını bir algoritmaya göre düşürür ancak veri kaybı olabilir.

from sklearn.decomposition import PCA

pca=PCA(n_components=2)

x_train_pca=pca.fit_transform(x_train)
x_test_pca=pca.transform(x_test)


In [19]:
#PCA dan önce LR
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression(random_state=18)

model_lr=lr.fit(x_train,y_train)

pred=model_lr.predict(x_test)

In [20]:
#PCA dan sonra LR
from sklearn.linear_model import LogisticRegression

lr_pca=LogisticRegression(random_state=18)

model_lr_pca=lr_pca.fit(x_train_pca,y_train)

pred_pca=model_lr_pca.predict(x_test_pca)

In [21]:
from sklearn.metrics import confusion_matrix
print('Gerçek değer ve PCA olmadan tahmin')
cm=confusion_matrix(y_test,pred)
cm

Gerçek değer ve PCA olmadan tahmin


array([[16,  1,  0],
       [ 0, 14,  0],
       [ 0,  0,  5]], dtype=int64)

In [22]:

print('Gerçek değer ve PCA tahmin')
cm_pca=confusion_matrix(y_test,pred_pca)
cm_pca

Gerçek değer ve PCA tahmin


array([[17,  0,  0],
       [ 0, 14,  0],
       [ 0,  0,  5]], dtype=int64)

In [23]:
print('PCA olmadan ve PCA tahmin')
cm=confusion_matrix(pred,pred_pca)
cm

PCA olmadan ve PCA tahmin


array([[16,  0,  0],
       [ 1, 14,  0],
       [ 0,  0,  5]], dtype=int64)

In [24]:
#LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda=LDA(n_components=2)
x_train_lda=lda.fit_transform(x_train,y_train)
x_test_lda=lda.transform(x_test)

lr_lda=LogisticRegression(random_state=18)
model_lr_lda=lr_lda.fit(x_train_lda,y_train)

pred_lda=model_lr_lda.predict(x_test_lda)


In [25]:
cm=confusion_matrix(pred,pred_lda)
cm

array([[16,  0,  0],
       [ 1, 14,  0],
       [ 0,  0,  5]], dtype=int64)

In [26]:
#Bu veride pca güzel sonuç verdi lda ve orjinal veride bir hata yaptı